const colors = {
  light: {
    text: "#0a0a0a",
    tint: "#FF6B00",
    background: "#F5F5F5",
    foreground: "#0A0A0A",
    card: "#FFFFFF",
    cardForeground: "#0A0A0A",
    primary: "#FF6B00",
    primaryForeground: "#FFFFFF",
    secondary: "#E8E8E8",
    secondaryForeground: "#1A1A1A",
    muted: "#E8E8E8",
    mutedForeground: "#737373",
    accent: "#FF6B00",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#D4D4D4",
    input: "#E8E8E8",
    success: "#22C55E",
    warning: "#F59E0B",
  },
  dark: {
    text: "#FAFAFA",
    tint: "#FF6B00",
    background: "#0A0A0A",
    foreground: "#FAFAFA",
    card: "#141414",
    cardForeground: "#FAFAFA",
    primary: "#FF6B00",
    primaryForeground: "#FFFFFF",
    secondary: "#1C1C1C",
    secondaryForeground: "#FAFAFA",
    muted: "#1C1C1C",
    mutedForeground: "#A0A0A0",
    accent: "#FF6B00",
    accentForeground: "#FFFFFF",
    destructive: "#EF4444",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A2A",
    input: "#1C1C1C",
    success: "#22C55E",
    warning: "#F59E0B",
  },
  radius: 12,
};

export default colors;
